/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PhasesRouteImport } from './routes/phases'
import { Route as IndexRouteImport } from './routes/index'

const PhasesRoute = PhasesRouteImport.update({
  id: '/phases',
  path: '/phases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/phases': typeof PhasesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/phases': typeof PhasesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/phases': typeof PhasesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/phases'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/phases'
  id: '__root__' | '/' | '/phases'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PhasesRoute: typeof PhasesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/phases': {
      id: '/phases'
      path: '/phases'
      fullPath: '/phases'
      preLoaderRoute: typeof PhasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PhasesRoute: PhasesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
