/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopologyRouteImport } from './routes/topology'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as PhasesRouteImport } from './routes/phases'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as FlowsRouteImport } from './routes/flows'
import { Route as AdvancedRouteImport } from './routes/advanced'
import { Route as IndexRouteImport } from './routes/index'

const TopologyRoute = TopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PhasesRoute = PhasesRouteImport.update({
  id: '/phases',
  path: '/phases',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsRoute = FlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedRoute = AdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedRoute
  '/flows': typeof FlowsRoute
  '/network': typeof NetworkRoute
  '/phases': typeof PhasesRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/topology': typeof TopologyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedRoute
  '/flows': typeof FlowsRoute
  '/network': typeof NetworkRoute
  '/phases': typeof PhasesRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/topology': typeof TopologyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedRoute
  '/flows': typeof FlowsRoute
  '/network': typeof NetworkRoute
  '/phases': typeof PhasesRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/topology': typeof TopologyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advanced'
    | '/flows'
    | '/network'
    | '/phases'
    | '/roadmap'
    | '/security'
    | '/topology'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advanced'
    | '/flows'
    | '/network'
    | '/phases'
    | '/roadmap'
    | '/security'
    | '/topology'
  id:
    | '__root__'
    | '/'
    | '/advanced'
    | '/flows'
    | '/network'
    | '/phases'
    | '/roadmap'
    | '/security'
    | '/topology'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvancedRoute: typeof AdvancedRoute
  FlowsRoute: typeof FlowsRoute
  NetworkRoute: typeof NetworkRoute
  PhasesRoute: typeof PhasesRoute
  RoadmapRoute: typeof RoadmapRoute
  SecurityRoute: typeof SecurityRoute
  TopologyRoute: typeof TopologyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topology': {
      id: '/topology'
      path: '/topology'
      fullPath: '/topology'
      preLoaderRoute: typeof TopologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phases': {
      id: '/phases'
      path: '/phases'
      fullPath: '/phases'
      preLoaderRoute: typeof PhasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows': {
      id: '/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof FlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced': {
      id: '/advanced'
      path: '/advanced'
      fullPath: '/advanced'
      preLoaderRoute: typeof AdvancedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvancedRoute: AdvancedRoute,
  FlowsRoute: FlowsRoute,
  NetworkRoute: NetworkRoute,
  PhasesRoute: PhasesRoute,
  RoadmapRoute: RoadmapRoute,
  SecurityRoute: SecurityRoute,
  TopologyRoute: TopologyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
